### ISSUE TITLE
Not able to compile Video encoding sample with custom/predefined preset

### ISSUE THREAD

**Issue by yugandhar02** [Azure-Samples/media-services-v3-java#85]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> try running mvn clean compile

### Any log messages given by the failure
```
>[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project EncodingWithMESPredefinedPreset: Compilation failure: Compilation failure:
[ERROR] /media-services-v3-java/VideoEncoding/EncodingWithMESPredefinedPreset/src/main/java/sample/EncodingWithMESPredefinedPreset.java:[15,30] package com.azure.storage.blob does not exist
[ERROR] /media-services-v3-java/VideoEncoding/EncodingWithMESPredefinedPreset/src/main/java/sample/EncodingWithMESPredefinedPreset.java:[16,30] package com.azure.storage.blob does not exist
[ERROR] /media-services-v3-java/VideoEncoding/EncodingWithMESPredefinedPreset/src/main/java/sample/EncodingWithMESPredefinedPreset.java:[17,30] package com.azure.storage.blob does not exist
[ERROR] -> [Help 1]
```

### Expected/desired behavior
> Should compile without any error

### OS and Version?
> macOS big sur

### Versions
>

### Mention any other details that might be useful
After adding 
```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.azure</groupId>
                <artifactId>azure-sdk-bom</artifactId>
                <version>1.0.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
    </dependencyManagement>
```
it compiles successfully but on executing "mvn exec:java" gets below error
```
java.lang.RuntimeException: java.io.IOException: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes
	at rx.exceptions.Exceptions.propagate(Exceptions.java:57)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:463)
	at rx.observables.BlockingObservable.first(BlockingObservable.java:166)
	at sample.EncodingWithMESCustomPreset.createCustomTransform(EncodingWithMESCustomPreset.java:226)
	at sample.EncodingWithMESCustomPreset.runEncodingWithMESCustomPreset(EncodingWithMESCustomPreset.java:107)
	at sample.EncodingWithMESCustomPreset.main(EncodingWithMESCustomPreset.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by ankumalh** [comment]
edit pom to add this dep mentioned here https://docs.microsoft.com/en-us/java/api/overview/azure/storage-blob-readme?view=azure-java-stable.  ```
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-storage-blob</artifactId>
    <version>12.14.1</version>
</dependency>
```

**Comment by yugandhar02** [comment]
After adding direct dependency as suggested by @ankumalh 
I am getting below error. I have re-checked configuration and seems to be correct

```
java.lang.IllegalArgumentException: Invalid connection string.
	at com.azure.storage.common.implementation.connectionstring.StorageConnectionString.create(StorageConnectionString.java:115)
	at com.azure.storage.blob.BlobContainerClientBuilder.connectionString(BlobContainerClientBuilder.java:293)
	at sample.EncodingWithMESCustomPreset.createInputAsset(EncodingWithMESCustomPreset.java:362)
	at sample.EncodingWithMESCustomPreset.runEncodingWithMESCustomPreset(EncodingWithMESCustomPreset.java:111)
	at sample.EncodingWithMESCustomPreset.main(EncodingWithMESCustomPreset.java:70)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

I can see it was authenticated correctly and transform was created successfully but was unable to upload asset because of above error
